### ISSUE TITLE
Version 2.0.1 not working in "seating chart" - "edit character" mode in Party.

### ISSUE THREAD

**Issue by AdaBallard** [ManlyMarco/KK_HeightBar#1]
When you enable "Show the height measure bar" while edting a character in existing class, a bar appears under the character's feet. But it has no numbers and it moves with the character when you move the camera. 

Previous version worked fine there.

It works fine in character editor when you launch it from main menu though ("Create character" - "Female").

Please fix it.

**Comment by ManlyMarco** [comment]
Fixed in 2.0.2
